services:
  tester-go:
    build:
      context: ../../../../src/asya-gateway
      dockerfile: Dockerfile
      target: tester
    depends_on:
      postgres:
        condition: service_healthy
      tester-py:
        condition: service_completed_successfully
    env_file:
    - ../../../shared/compose/envs/.env.${ASYA_TRANSPORT}
    - ../../../shared/compose/envs/.env.postgres
    - ../../../shared/compose/envs/.env.tester
    - ../../../shared/compose/envs/.env.asya-shared
    volumes:
    - ../../../../testing/component/gateway/tests_go:/build/tests:ro
    working_dir: /build
    entrypoint: /bin/sh
    command:
    - -c
    - |
      set -ex
      if [ "$ASYA_TRANSPORT" = "rabbitmq" ]; then
        go test -tags=integration -v -run 'TestChannelPool|TestRabbitMQ' ./tests/queue/...
      elif [ "$ASYA_TRANSPORT" = "sqs" ]; then
        go test -tags=integration -v -run 'TestSQS' ./tests/queue/...
      fi
      go test -tags=integration -v ./tests/envelopestore/...
