name: "Setup Environment"
description: "Sets up Python, Go, and dependencies"
inputs:
  install-docker:
    description: "Install Docker buildx"
    required: false
    default: "false"
  install-kind:
    description: "Install Kind"
    required: false
    default: "false"
  install-helm:
    description: "Install Helm and Helmfile"
    required: false
    default: "false"
  cache-precommit:
    description: "Cache pre-commit environments"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v6
    with:
      version: "0.9.1"
      enable-cache: true
      cache-dependency-glob: |
        **/requirements*.txt
        **/pyproject.toml

  - name: Set up Python
    shell: bash
    run: uv python install 3.13

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: "1.23"
      cache: true
      cache-dependency-path: |
        src/asya-gateway/go.sum
        src/asya-sidecar/go.sum
        src/asya-operator/go.sum

  - name: Extract tool versions from Makefile
    id: tool-versions
    shell: bash
    run: |
      GOIMPORTS_VERSION=$(grep '^GOIMPORTS_VERSION :=' Makefile | awk '{print $3}' || echo "unknown")
      GOLANGCI_VERSION=$(grep '^GOLANGCI_LINT_VERSION :=' Makefile | awk '{print $3}' || echo "unknown")
      echo "goimports=$GOIMPORTS_VERSION" >> $GITHUB_OUTPUT
      echo "golangci=$GOLANGCI_VERSION" >> $GITHUB_OUTPUT

  - name: Cache Go tools
    uses: actions/cache@v4
    with:
      path: ~/go/bin
      key: go-tools-${{ runner.os }}-goimports-${{ steps.tool-versions.outputs.goimports }}-golangci-${{ steps.tool-versions.outputs.golangci
        }}

  - name: Cache pre-commit environments
    if: inputs.cache-precommit == 'true'
    uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      restore-keys: |
        precommit-${{ runner.os }}-

  - name: Install dependencies
    shell: bash
    run: |
      uv venv
      source .venv/bin/activate
      make setup

  - name: Set up Docker buildx
    if: inputs.install-docker == 'true'
    uses: docker/setup-buildx-action@v3

  - name: Install Kind
    if: inputs.install-kind == 'true'
    uses: helm/kind-action@v1
    with:
      install_only: true
      version: v0.25.0

  - name: Install Helm
    if: inputs.install-helm == 'true'
    uses: azure/setup-helm@v4
    with:
      version: v3.16.3

  - name: Install Helmfile
    if: inputs.install-helm == 'true'
    uses: helmfile/helmfile-action@v1
    with:
      helmfile-version: v0.169.2
      helm-version: v3.16.3
      helm-plugins: https://github.com/databus23/helm-diff --version v3.8.1
