# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../text_analysis_flow.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../text_analysis_flow.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_text_analysis_flow(envelope: dict) -> dict:
    """Entrypoint for flow 'text_analysis_flow'"""
    r = envelope['route']
    c = r['current']

    r['actors'][c+1:c+1] = [resolve("clean_text"), resolve("tokenize"), resolve("router_text_analysis_flow_line_9_if")]
    r['current'] = c + 1
    return envelope

def router_text_analysis_flow_line_14_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['sentiment'] = 'neutral'
    _next.append(resolve("extract_entities"))
    _next.append(resolve("router_text_analysis_flow_line_18_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_text_analysis_flow_line_11_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    if p['language'] == 'es':
        _next.append(resolve("spanish_sentiment"))
        _next.append(resolve("extract_entities"))
        _next.append(resolve("router_text_analysis_flow_line_18_seq"))
    else:
        _next.append(resolve("router_text_analysis_flow_line_14_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_text_analysis_flow_line_18_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['extracted'] = True

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_text_analysis_flow_line_9_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    if p['language'] == 'en':
        _next.append(resolve("english_sentiment"))
        _next.append(resolve("extract_entities"))
        _next.append(resolve("router_text_analysis_flow_line_18_seq"))
    else:
        _next.append(resolve("router_text_analysis_flow_line_11_if"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def end_text_analysis_flow(envelope: dict) -> dict:
    """Exitpoint for flow 'text_analysis_flow'"""
    return envelope


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
