version: 2

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly
  concurrency: 3

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
  - errcheck # Check error returns are handled
  - gosec # Security-focused linter
  #- contextcheck    # Ensure contexts are properly propagated
  - staticcheck # Advanced static analysis
  - govet # Standard Go vet
  #- revive          # Fast, configurable linter
  - gocyclo # Cyclomatic complexity
  - goconst # Repeated strings that should be constants
  - misspell # Spelling mistakes
  #- unparam         # Unused function parameters
  #- nilnil          # Prevent (nil, nil) returns
  - nolintlint # Validate //nolint directives
  #- unused          # Disabled: excessive memory usage on CI (golangci-lint#898, #3565)
  - ineffassign # Detect ineffectual assignments

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  gosec:
    excludes:
    - G404 # Use of weak random number generator (math/rand) - often fine for non-crypto uses
    - G112 # HTTP server timeouts (can be set at deploy time)
    - G306 # File permissions (0644 is fine for non-sensitive files)
    - G304 # File inclusion via variable (needed for config loading)
    - G115 # Integer overflow conversion (often safe in practice)
    - G204 # Subprocess with variable (safe in tests)

  contextcheck:
    check-generated: false

  gocyclo:
    min-complexity: 30

  goconst:
    min-len: 3
    min-occurrences: 3

  revive:
    rules:
    - name: error-return
    - name: error-naming
    - name: error-strings
    - name: exported
    - name: increment-decrement
    - name: var-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
  # Exclude test files from some checks
  - path: _test\.go
    linters:
    - gocyclo
    - errcheck
    - gosec
